### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by BenGardiner**
* add the toolchain test ppa using the travis declaratives to get 4.7
* build libusb 1.x from wget https://github.com/libusb/libusb/archive/v1.0.19.tar.gz as in the instructions here: http://gimx.fr/wiki/index.php?title=Bbb_sniffer (I've had build errors with ubuntu 12.04's libusb-1.0-0-dev

### CODE REVIEW

**Comment by dominicgs** [comment]
I like that this fixes travis, but I'm not sure that I like removing the compiler check.  This won't build with older compilers and I'm a fan of the "fail early" method.  Do you have any suggestions of alternative ways to fix the problem?

**Comment by BenGardiner** [comment]
No problem.

I hope breaking from the built-in CMake CXX version variable and building one ourselves out of -dumpversion output will do the trick.

**Comment by BenGardiner** [comment]
Ping.

Hi @dominicgs, I think I resolved this issue you raised on Oct 23, 2015. Please let me know if there is something else you'd like for this PR to be acceptable.

**Comment by dominicgs** [comment]
@BenGardiner Sorry, I completely forgot!  Merged now, thank you very much for your contribution.

**Pull request merged**
