### PR TITLE
Fixed typo and the error for "usb-mitm -i"

### PR DESCRIPTION
**Pull request by potjaune**

### CODE REVIEW

**Comment by dominicgs** [comment]
Looks reasonable to me.  Does this fix the issue reported to the mailing list?

**Comment by potjaune** [comment]
More or less, it solved one problem, but now I am getting "Packet returned due to full pipe & buffer" when I use netcat to inject packets.

**Comment by potjaune** [comment]
Would you happen to know how to solve this "Packet returned due to full piper & buffer" problem? I was looking at your ShmooCon demo video, and replicated the exact same commands with the ShmooCon tag, and I seem to get the same problem and was not able to inject the letter 'a'.

**Comment by dominicgs** [comment]
I haven't seen that error before.  Do you see that on the host running netcat or on the BBB?

**Comment by potjaune** [comment]
On the BBB. 
I've also tried hard coding injection letter 'a' like so, 

	__u8 data[8] = {0x00,0x00,0x04,0x00,0x00,0x00,0x00,0x00};
		*packet=new Packet(0x81, data , 8, false);
		(*packet)->transmit=true;
		return;

But unfortunately, the same message pops up and nothing is injected.

**Comment by dominicgs** [comment]
I was concerned that we'd broken the injectors, but if the Shmoocon tag doesn't work, I assume that it's not that.

Are you using the OS image published on the releases page?  It contains settings and patches to make usb-mitm work correctly.

**Comment by potjaune** [comment]
Yea I am using that OS, if this helps here is the output:

root@arm:/home/debian/USBProxy/src/build# usb-mitm -i -k
SIGRTMIN: 34
CP: Vector Plugins
CP: String Injector_UDP::Port = 12345
CP: Vector Plugins
CP: Pointer PacketFilter_KeyLogger::file
CP: Vector Plugins
CP: String DeviceProxy = DeviceProxy_LibUSB
CP: String HostProxy = HostProxy_GadgetFS
Loading plugins from /usr/local/lib/USBProxy/
vendorId=ffffffff
productId=ffffffff
cleaning up /tmp
removing 0
Made directory /tmp/gadget-STFUVA for gadget
Printing Config data
	Strings: 3
		DeviceProxy: DeviceProxy_LibUSB
		HostProxy: HostProxy_GadgetFS
		Injector_UDP::Port: 12345
	Vectors: 1
		Plugins:
			Injector_UDP
			PacketFilter_KeyLogger
			PacketFilter_ROT13
Pointer: 1
		PacketFilter_KeyLogger::file: 0xb6d66540
Made directory /tmp/mqueue-qg2ag5 for mqueue
cleaning up /tmp/mqueue-qg2ag5
removing 0
Device: 12 01 00 02 00 00 00 08 f0 03 24 00 30 01 01 02 00 01
  Manufacturer: CHICONY
  Product:      HP Basic USB Keyboard
	*Config(1): 09 02 22 00 01 01 00 a0 32
		Interface(0):
			*Alt(0): 09 04 00 00 01 03 01 01 00
				HID: 09 21 11 01 00 01 22 41 00
				EP(81): 07 05 81 03 08 00 0a
searching in [/tmp/gadget-STFUVA]
Starting injector thread (6258) for [Injector].
Opening injection UDP socket on port 12345.
Injector In FD[1/1]: 18
Starting setup writer thread (6260) for EP00.
Starting setup reader thread (6259) for EP00.
Opened EP81
Starting writer thread (6262) for EP81.
Starting reader thread (6261) for EP81.
Packet returned due to full pipe & buffer

**Comment by dominicgs** [comment]
Does it proxy traffic as expected?  i.e. are the keyboard key presses passed through?

**Comment by potjaune** [comment]
Yes, the keyboard passes through. According to the comments, the error may be due either to the new queue not being defined or the buffer is already in use,. do you have any insight about this?
Could it also be a windows driver related issue?

**Comment by dominicgs** [comment]
I think it's most likely to be a bug in USBProxy or the setup on the BBB, but I can't seem to replicate it.

**Comment by Mar10us** [comment]
Is it possible the injectors are missing their queue's e.g. not set?

**Comment by matiaso** [comment]
I encounter the same issue and I have noticed that mqueue was removed. In the video we can see that a mqueue folder is created and this is not the case anymore.

In the SchmooCon_2015 version the mqueue is still created, no error messages are returned but the injection is not working.

**Pull request merged**
